# Experiment config for evaluating a discrete VLN agent in VLN-CE.
#     Subgoals: Subgoal Generation Module (SGM)
#    VLN agent: Recurrent VLN-BERT w/ Habitat vision
#   Navigation: Local Policy (LP)

BASE_TASK_CONFIG_PATH: habitat_extensions/config/vln_harness_sgm_local_policy_task.yaml
ENV_NAME: LPEnv
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 5
EVAL_CKPT_PATH_DIR: data/models/RecVLNBERT-ce_vision.pth
RESULTS_DIR: data/results/RecVLNBERT-ce_vision/sgm-local_policy
LOCAL_POLICY: True

EVAL:
  SPLIT: val_unseen
  SAVE_NAV_STATS: True

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [
        ObsStack,
        Laser2D,
        RadialOccupancy,
        ResNetAllEncoder,
        SubgoalModule,
        PreprocessVLNInstruction,
      ]
