ENVIRONMENT:
  MAX_EPISODE_STEPS: 25

SIMULATOR:
  TURN_ANGLE: 15
  FORWARD_STEP_SIZE: 0.25
  ACTION_SPACE_CONFIG: v0
  AGENT_0:
    SENSORS: [RGB_SENSOR]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 75
    POSITION: [0, 1.5, 0]  # mean height of viewpoints in MP3D-Sim
TASK:
  TYPE: VLN-v0
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT]
  SUCCESS_DISTANCE: 3.0

  SENSORS: [
    VLN_INSTRUCTION_SENSOR,
    VLN_CANDIDATE_SENSOR,
    MP3D_ACTION_ANGLE_SENSOR,
  ]

  MEASUREMENTS: [
    STEPS_TAKEN,
    PATH_LENGTH,
    DISTANCE_TO_GOAL,
    ORACLE_NAVIGATION_ERROR,
    SUCCESS,
    ORACLE_SUCCESS,
    SPL,
  ]

  TOP_DOWN_MAP_VLNCE:
    MAX_EPISODE_STEPS: 150
    DRAW_SHORTEST_PATH: False
    DRAW_REFERENCE_PATH: True
    DRAW_MP3D_AGENT_PATH: False
    FOG_OF_WAR:
      FOV: 360
      VISIBILITY_DIST: 4.8

  SUCCESS:
    SUCCESS_DISTANCE: 3.0

DATASET:
  TYPE: VLN-CE-v1
  SPLIT: train
  DATA_PATH: data/datasets/R2R_VLNCE_v1-3/{split}/{split}.json.gz
  SCENES_DIR: data/scene_datasets/
