BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_waypoint_task.yaml
TRAINER_NAME: ddppo-waypoint
ENV_NAME: VLNCEWaypointEnv
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 4
TENSORBOARD_DIR: data/tensorboard_dirs/wpn_cc
CHECKPOINT_FOLDER: data/checkpoints/wpn_cc
EVAL_CKPT_PATH_DIR: data/checkpoints/wpn_cc

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ObsStack]

MODEL:
  policy_name: WaypointPolicy

  WAYPOINT:
    min_offset_var: 0.00030625  # stddev of 1 degree
    max_offset_var: 0.06853892  # stddev of (range / 2)
    offset_temperature: 4.0
    min_distance_var: 0.01  # a stddev of 0.10m
    max_distance_var: 3.516  # a stddev of (range / 2)
    max_distance_prediction: 4.0
    min_distance_prediction: 0.25

  INSTRUCTION_ENCODER:
    bidirectional: True
    final_state_only: False

  RGB_ENCODER:
    cnn_type: TorchVisionResNet18
    output_size: 128

  STATE_ENCODER:
    hidden_size: 256
