BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_waypoint_task.yaml
TRAINER_NAME: ddppo-waypoint
ENV_NAME: VLNCEWaypointEnv
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 4
TENSORBOARD_DIR: data/tensorboard_dirs/wpn_dc
CHECKPOINT_FOLDER: data/checkpoints/wpn_dc
EVAL_CKPT_PATH_DIR: data/checkpoints/wpn_dc

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ObsStack]

  PPO:
    pano_entropy_coef: 1.5
    offset_entropy_coef: 1.0
    distance_entropy_coef: 1.0

MODEL:
  policy_name: WaypointPolicy

  WAYPOINT:
    continuous_distance: False

  INSTRUCTION_ENCODER:
    bidirectional: True
    final_state_only: False

  RGB_ENCODER:
    cnn_type: TorchVisionResNet18
    output_size: 128

  STATE_ENCODER:
    hidden_size: 256
