BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_waypoint_task.yaml
TRAINER_NAME: ddppo-waypoint
ENV_NAME: VLNCEWaypointEnv
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 4
TENSORBOARD_DIR: data/tensorboard_dirs/hpn___
CHECKPOINT_FOLDER: data/checkpoints/hpn___
EVAL_CKPT_PATH_DIR: data/checkpoints/hpn___

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ObsStack]

  PPO:
    pano_entropy_coef: 1.5

MODEL:
  policy_name: WaypointPolicy

  WAYPOINT:
    predict_distance: False
    predict_offset: False

  INSTRUCTION_ENCODER:
    bidirectional: True
    final_state_only: False

  RGB_ENCODER:
    cnn_type: TorchVisionResNet18
    output_size: 128

  STATE_ENCODER:
    hidden_size: 256
